apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: aws-eks-example
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta2
      kind: AWSManagedControlPlaneTemplate
      name: "eks-control-plane"
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSManagedClusterTemplate
      name: "eks-cluster"
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              name: "eks-md-0"
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
              kind: EKSConfigTemplate
          infrastructure:
            ref:
              name: "eks-md-0"
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
              kind: AWSMachineTemplate
  variables:
    - name: region
      required: true
      schema:
        openAPIV3Schema:
          description: "The AWS region where the Cluster will be created"
          type: string
    - name: sshKeyName
      required: false
      schema:
        openAPIV3Schema:
          description: "AWS SSH key name to use"
          type: string
          default: ''
    - name: instanceType
      required: false
      schema:
        openAPIV3Schema:
          description: "AWS instance type to use"
          type: string
          default: "t3.xlarge"
    - name: eksClusterName
      required: false
      schema:
        openAPIV3Schema:
          description: "EKS cluster name"
          type: string
          default: ''
    - name: awsClusterIdentityName
      required: true
      schema:
        openAPIV3Schema:
          description: The AWSClusterStaticIdentity resource name referencing the credentials to create the Cluster.
          type: string
          default: cluster-identity
  patches:
    - name: awsManagedControlPlaneTemplate
      definitions:
      - selector:
          apiVersion: controlplane.cluster.x-k8s.io/v1beta2
          kind: AWSManagedControlPlaneTemplate
          matchResources:
            controlPlane: true
        jsonPatches:
          - op: add
            enabledIf: '{{ ne .eksClusterName }}'
            path: /spec/template/spec/eksClusterName
            valueFrom:
              variable: eksClusterName
          - op: add
            path: /spec/template/spec/region
            valueFrom:
              variable: region
          - op: add
            enabledIf: '{{ ne .sshKeyName }}'
            path: /spec/template/spec/sshKeyName
            valueFrom:
              variable: sshKeyName
          - op: add
            path: /spec/template/spec/identityRef/name
            valueFrom:
              variable: awsClusterIdentityName
          # Builtins
          - op: add
            path: "/spec/template/spec/version"
            valueFrom:
              variable: builtin.cluster.topology.version
    - name: awsMachineTemplate
      definitions:
      - selector:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
          kind: AWSMachineTemplate
          matchResources:
            machineDeploymentClass:
              names:
              - default-worker
        jsonPatches:
          - op: add
            enabledIf: '{{ ne .sshKeyName }}'
            path: /spec/template/spec/sshKeyName
            valueFrom:
              variable: sshKeyName
          - op: add
            path: /spec/template/spec/instanceType
            valueFrom:
              variable: instanceType
---
kind: AWSManagedClusterTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: "eks-cluster"
spec:
  template:
    spec: {}
---
kind: AWSManagedControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
metadata:
  name: "eks-control-plane"
spec:
  template:
    spec:
      region: "replaced_by_patch"
      version: "v0.0.0" # To be replaced by patch
      identityRef:
        kind: AWSClusterStaticIdentity
        name: cluster-identity
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: "eks-md-0"
spec:
  template:
    spec:
      instanceType: "replaced_by_patch"
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: EKSConfigTemplate
metadata:
  name: "eks-md-0"
spec:
  template:
    spec: {}
