{{- if index .Values "rancherTurtles" "features" "embedded-operator" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterctl-config
  namespace: '{{ .Values.rancherTurtles.namespace }}'
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-1"
{{- end}}