name: dependabot

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]
    branches:
      - dependabot/**
  push:
    branches:
      - dependabot/**
  workflow_dispatch:

permissions:
  contents: write # Allow to update the PR.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # tag=v3.5.0
      with:
        go-version-file: go.mod
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.2
    - name: Update generated code
      run: make generate
    - name: Commit changes
      run: |
        git config --local user.email "49699333+dependabot[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        [[ -z "$(git status -s)" ]] || git commit -m "Update generated code" -s
        git push
